pipeline {
   tools {nodejs "node"}
   stage('Preparation') {
     checkout scm
   }
   stage('Install dependencis') {
     steps {
       sh 'npm install'
     }
   }
    stage('Install dependencis') {
     steps {
       sh 'npm test'
     }
   }
}