node {
   stage('Preparation') {
     checkout scm
   }
   stage('Install dependencis') {
     step {
       sh 'npm install'
     }
   }
    stage('Install dependencis') {
     step {
       sh 'npm test'
     }
   }
}